# Generated by Django 3.1.2 on 2021-10-31 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholar',
            old_name='subject',
            new_name='latestJob',
        ),
        migrations.AddField(
            model_name='scholar',
            name='programmeName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='sharing',
            field=models.CharField(default='te', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='thesisTitle',
            field=models.CharField(default='tr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='year_end',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='year_start',
            field=models.IntegerField(default=2100),
            preserve_default=False,
        ),
    ]
