# Generated by Django 3.1.2 on 2021-10-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_auto_20211031_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='scholarshipName',
            field=models.CharField(default='Granite Pearls', max_length=100),
            preserve_default=False,
        ),
    ]
