# Generated by Django 3.1.2 on 2021-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholar_scholarshipname'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='scholar/'),
        ),
    ]
