# Generated by Django 3.1.2 on 2021-11-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_scholar_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='latestJob',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='programmeName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='sharing',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='thesisTitle',
            field=models.CharField(max_length=500),
        ),
    ]
