# Generated by Django 3.1.2 on 2021-11-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_auto_20211101_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='latestJob',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='thesisTitle',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
