# Generated by Django 3.1.2 on 2021-11-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_auto_20211121_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='programmeName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='scholarshipName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
