# Generated by Django 3.1.2 on 2021-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0008_auto_20211121_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='status',
            field=models.CharField(default='past', max_length=50),
        ),
    ]
