# Generated by Django 3.1.2 on 2021-11-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postComment', to='blog.post'),
        ),
    ]
